#!/bin/bash

source /etc/os-release # Importing the file with the OS infos

# <--- Declaring the colors --->
RESET="\e[0m"
BOLD="\e[1m"		# Title Colors
BGBLUE="\033[44m"
# ----------------
GREEN="\e[32m"
RED="\e[31m"   		# Monitoring Colors
YELLOW="\e[33m"
# ----------------
BLUE="\033[0;34m"	# Main Color
# ----------------

echo ""

DEVICENAME="${USER}@$(uname -n)"
len=${#DEVICENAME}
echo -e "${BOLD}${BGBLUE}$DEVICENAME${RESET}"
printf "%${len}s\n" | tr ' ' '-'

# <--- System Informations --->
echo -e "${BLUE}OS:${RESET} ${PRETTY_NAME}"
echo -e "${BLUE}Shell:${RESET} $(basename $SHELL) ${BASH_VERSION}"
echo -e "${BLUE}CPU:${RESET} "
